language: node_js

cache:
  yarn: true
  directories:
    - ~/.cache

notifications:
  email: false

sudo: false

jobs:
  include:
    - stage: lint
      script: commitlint-travis
    - &test
      node_js: '11'
      stage: test
      install: yarn
      script: yarn test
      cache:
        directories:
          - ~/.npm
          - node_modules

    - <<: *test
      node_js: '10'
    - <<: *test
      node_js: '9'
    - <<: *test
      node_js: '8'
    - stage: npm release
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on: semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - lint
  - test
  - name: npm release
    if: branch = master
