language: node_js

cache:
  yarn: true
  directories:
    - ~/.cache
    - node_modules

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

notifications:
  email: false

sudo: false

jobs:
  include:
    - stage: lint
      node_js: '12'
      script: commitlint-travis

    - &test
      node_js: '12'
      stage: test
      install: yarn
      script: yarn test
    - <<: *test
      node_js: '11'
    - <<: *test
      node_js: '10'

    - stage: npm release
      node_js: '12'
      before_install: yarn global add greenkeeper-lockfile@1
      before_script: greenkeeper-lockfile-update
      script:
        - yarn build
        - yarn semantic-release
      after_script: greenkeeper-lockfile-upload

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - lint
  - test
  - name: npm release
    if: branch = master
