language: node_js

cache:
  yarn: true
  directories:
    - ~/.cache

notifications:
  email: false

node_js:
  - '11'
  - '10'
  - '9'
  - '8'

sudo: false

jobs:
  include:
    - stage: lint
      script: commitlint-travis
    - stage: test
      script: yarn test
    - stage: npm release
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on: semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - lint
  - test
  - name: npm release
    if: branch = master
